### ISSUE TITLE
Unable to see failures summarized at the end

### ISSUE THREAD

**Issue by rezammalik** [kotest/kotest-gradle-plugin#11]
I am not seeing failures summarized at the end of the test runs. I am using this with Gradle 4.4.3 though. Is this something that would work only with Gradle version specified in the README?

**Comment by sksamuel** [comment]
Gradle 4.4.3 is quite old. This plugin is only targeting 6.x
Can you upgrade? If you're using the gradle wrapper it should be straightforward?

**Comment by rezammalik** [comment]
oh, I misspoke. I meant I am using Kotest 4.4.3 and Gradle 6.8.2.

**Comment by sksamuel** [comment]
So like a section that sums it up ?
The reporter should already be doing that. Do you have a screenshot ?

**Comment by rezammalik** [comment]
Here is a use case, 4 tests, 2 per Class are run. 

The first one is good with both tests passing, the second one has 2 assertions in 1 test fail (reported together via softAsserts), the second test in the file just has one assert fail, shows correctly. 
````
2.  testy.TestClass2
    + Account created via endpoint
        + for user2
            + on Internal Endpoint
                - returns the correct response and passes data validation OK (1411ms)
            + on Gateway Endpoint
                - returns the correct response and passes data validation OK (1577ms)

3.  testy.TestClass1
    + Account created via endpoint
        + for user 1
            + on Internal Endpoint
                - returns the correct response and passes data validation FAILED (1303ms)


The following 2 assertions failed:
1) expected:<"FAILED"> but was:<"SUCCESS">
        at testy.TestClass1$1$1$2$1$1.invokeSuspend(TestClass1.kt:82)
2) expected:<"FAILED"> but was:<"SUCCESS">
        at testy.TestClass1$1$1$2$1$1.invokeSuspend(TestClass1.kt:84)

<... stack trace here>

            + on Gateway Endpoint
                - returns the correct response and passes data validation FAILED (1579ms)

expected:<"FAILED"> but was:<"SUCCESS">
<... stack trace here>

>> There were test failures

 testy.TestClass1
 - Account created via endpoint for user 1 on Internal Endpoint returns the correct response and passes data validation
 - Account created via endpoint for user 1 on Gateway Endpoint returns the correct response and passes data validation

Specs:   2 passed, 1 failed, 3 total
Tests:   2 passed, 2 failed, 0 ignored, 4 total
Time:    27s

> Task :kotest FAILED

FAILURE: Build failed with an exception.
````
I was expecting the the summary at the end to list the assertions that failed, like in the readme.md screengrabs. Just wondering if my expectations are off or there is something I am not doing correctly, for them to now show up.

**Comment by sksamuel** [comment]
I get you.

Good idea I'll add it.

**Comment by rezammalik** [comment]
Sweet. This seems like it went in and is appearing.

**Comment by rezammalik** [comment]
@sksamuel Hey Sam. Is this something that is available now or will be soon?
