### ISSUE TITLE
Compilation failed: Found class org.jetbrains.kotlin.ir.declarations.IrFactory, but interface was expected

### ISSUE THREAD

**Issue by CLOVIS-AI** [kotest/kotest-gradle-plugin#56]
When migrating a project to Kotlin 2.0.20, I get: 

```
> Task :core:compileTestKotlinJvm
e: Compilation failed: Found class org.jetbrains.kotlin.ir.declarations.IrFactory, but interface was expected
 * Source files: HelloWorldTest.kt
 * Compiler version: 2.0.20
> Task :core:compileTestKotlinLinuxX64 FAILED
 * Output kind: LIBRARY
e: java.lang.IncompatibleClassChangeError: Found class org.jetbrains.kotlin.ir.declarations.IrFactory, but interface was expected
	at io.kotest.framework.multiplatform.embeddablecompiler.NativeTransformer.generateLauncher(NativeTransformer.kt:46)
	at io.kotest.framework.multiplatform.embeddablecompiler.Transformer.visitModuleFragment(Transformer.kt:65)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitModuleFragment(IrElementTransformerVoid.kt:113)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitModuleFragment(IrElementTransformerVoid.kt:19)
	at org.jetbrains.kotlin.ir.declarations.IrModuleFragment.accept(IrModuleFragment.kt:33)
	at org.jetbrains.kotlin.ir.declarations.IrModuleFragment.transform(IrModuleFragment.kt:36)
	at io.kotest.framework.multiplatform.embeddablecompiler.SpecIrGenerationExtension.generate(SpecIrGenerationExtension.kt:23)
```

The offending file (comments removed):
```kotlin
package example

import opensavvy.prepared.runner.kotest.PreparedSpec

@Suppress("unused")
class HelloWorldTest : PreparedSpec({
	test("Call the 'foo' function") {
		foo()
	}

	test("Create an instance of the HelloWorld class") {
		HelloWorld()
	}
})
```

I don't know the compiler internals enough to be able to understand what the error message points to in this file.

Versions:
- Kotlin 2.0.20
- Kotest 5.9.1

Other info:
- [Full trace](https://gitlab.com/opensavvy/automation/gradle-conventions/-/jobs/7661132006#L708)
- [Build scan](https://scans.gradle.com/s/wrosek7psk6by/)

Reproduction:
- `git clone https://gitlab.com/opensavvy/automation/gradle-conventions.git`
- `git switch --detach e463ede01813cf57a9c6d21d7fd5f91de18ac229`
- `./gradlew build run -p examples/kotlin --include-build ../..`

**Comment by CLOVIS-AI** [comment]
Closing this as a duplicate of https://github.com/kotest/kotest/issues/4177
